package com.theironyard;

import javax.persistence.*;

@Entity //entity = an object you are trying to store. marking this as something we are going to be storing in the database
@Table(name = "messages") // table = specifies the table name.  when we make class message, we will store in table called messages
public class Message {
    @Id // identity column, special column
    @GeneratedValue // generated by the system
            Integer id;

    @Column(nullable = false) // @column maps a column in db table with this field in java,
            // specified that you can't pass null into this column
            String text;


    public Message() {
    }

    public Message(String text) {
        this.text = text;
    }
}

